nimbusletruand_curriculumvitae_default:
    path:       /{cvxmlfile}/{_locale}
    defaults:
        _controller:    NimbusletruandCurriculumVitaeBundle:Default:index
        _locale:        en
        cvxmlfile:      example