fabiencrassat_curriculumvitae_exportPDF:
    path:       /{cvxmlfile}/{_locale}/pdf
    defaults:
        _controller:    FabienCrassatCurriculumVitaeBundle:Default:exportPDF
        _locale:        en
        cvxmlfile:      example
fabiencrassat_curriculumvitae_default:
    path:       /{cvxmlfile}/{_locale}
    defaults:
        _controller:    FabienCrassatCurriculumVitaeBundle:Default:index
        _locale:        en
        cvxmlfile:      example
