parameters:
#    nimbusletruand_curriculumvitae.example.class: Nimbusletruand\CurriculumVitaeBundle
    nimbusletruand_curriculumvitae.path_to_cv: "../Resources/data/"

services:
#    nimbusletruand_curriculumvitae.example:
#        class: %nimbusletruand_curriculumvitae.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
