# .scrutinizer.yml
# inherit the next configuration down the chain
inherit: true

filter:
    excluded_paths:
        - "Resources/offline/js/bootstrap.min.js"

tools: ~
build:
    environment:
        php:
            version: 7.1
    tests:
        override:
            -
                command: phpunit --coverage-clover=my-coverage-file
                coverage:
                    file: my-coverage-file
                    format: php-clover
before_commands:
    - "composer install --prefer-source --dev"
