# .scrutinizer.yml
# inherit the next configuration down the chain
inherit: true

tools: ~
build:
    environment:
        php: '5.5.25'
    tests:
        override:
            -
                command: phpunit --coverage-clover=my-coverage-file
                coverage:
                    file: my-coverage-file
                    format: php-clover
before_commands:
    - "composer install --prefer-source --dev"
