# faster builds on new travis setup not using sudo
sudo: false
language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - nightly

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: TEST_FILES=true
    # test against the latest HHVM version by using trusty
    - php: hhvm
      sudo: true
      dist: trusty
      group: edge # Use edge image until the next travis CI image update
  allow_failures:
    - php: hhvm

addons:
  sonarcloud:
    organization: "fabiencrassat-github"
    token:
      secure: $SONAR_TOKEN

before_script: composer install

script:
  - if [[ $TEST_FILES != true ]]; then phpunit --coverage-text; fi
  - if [[ $TEST_FILES == true ]]; then phpunit --coverage-text --log-junit tests.junit.xml --coverage-clover coverage.clover.xml; fi
  - if [[ $TEST_FILES == true ]]; then sonar-scanner "-Dsonar.projectVersion=$(git describe --tags)+build.$TRAVIS_BUILD_NUMBER"; fi
